In [3]:
#Importing Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
!pip install mlflow

Collecting mlflow
  Downloading mlflow-3.1.4-py3-none-any.whl (24.7 MB)
     |████████████████████████████████| 24.7 MB 3.8 MB/s eta 0:00:01
Requirement already satisfied: pandas<3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.4.2)
Collecting graphene<4
  Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
     |████████████████████████████████| 114 kB 70.1 MB/s eta 0:00:01
Requirement already satisfied: matplotlib<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (3.5.1)
Requirement already satisfied: scikit-learn<2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.0.2)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.4.32)
Collecting alembic!=1.10.0,<2
  Downloading alembic-1.16.5-py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 77.8 MB/s eta 0:00:01
Collecting docker<8,>=4.0.0
  Downloading docker-7.1.0-py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 66.5 MB/s eta 0:00:01
Collecting pyarrow<21,>=4.0.0
  Downloading pyarrow-20.0.0-cp39-cp39-manylinux_2_28_x86_64.whl (42.3 MB)
     |████████████████████████████████| 42.3 MB 8.9 kB/s  eta 0:00:01     |██████████████████████▋         | 29.9 MB 33.1 MB/s eta 0:00:01     |███████████████████████▉        | 31.5 MB 33.1 MB/s eta 0:00:01     |███████████████████████████████▉| 42.1 MB 33.1 MB/s eta 0:00:01
Requirement already satisfied: numpy<3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.21.5)
Collecting mlflow-skinny==3.1.4
  Downloading mlflow_skinny-3.1.4-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 25.8 MB/s eta 0:00:01
Collecting gunicorn<24
  Downloading gunicorn-23.0.0-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 6.3 MB/s  eta 0:00:01
Requirement already satisfied: Flask<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.1.2)
Requirement already satisfied: scipy<2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow) (1.7.3)
Collecting pydantic<3,>=1.10.8
  Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
     |████████████████████████████████| 472 kB 84.4 MB/s eta 0:00:01
Collecting opentelemetry-sdk<3,>=1.9.0
  Downloading opentelemetry_sdk-1.41.1-py3-none-any.whl (180 kB)
     |████████████████████████████████| 180 kB 83.0 MB/s eta 0:00:01
Collecting gitpython<4,>=3.1.9
  Downloading gitpython-3.1.50-py3-none-any.whl (212 kB)
     |████████████████████████████████| 212 kB 83.5 MB/s eta 0:00:01
Requirement already satisfied: packaging<26 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (21.3)
Requirement already satisfied: click<9,>=7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (8.0.4)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (4.11.3)
Requirement already satisfied: requests<3,>=2.17.3 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (2.27.1)
Collecting sqlparse<1,>=0.4.0
  Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 6.6 MB/s  eta 0:00:01
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (4.1.1)
Collecting opentelemetry-api<3,>=1.9.0
  Downloading opentelemetry_api-1.41.1-py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 11.7 MB/s eta 0:00:01
Requirement already satisfied: pyyaml<7,>=5.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (6.0)
Collecting uvicorn<1
  Downloading uvicorn-0.39.0-py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 8.8 MB/s  eta 0:00:01
Collecting cachetools<7,>=5.0.0
  Downloading cachetools-6.2.6-py3-none-any.whl (11 kB)
Requirement already satisfied: protobuf<7,>=3.12.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (3.19.1)
Collecting fastapi<1
  Downloading fastapi-0.128.8-py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 79.9 MB/s eta 0:00:01
Requirement already satisfied: cloudpickle<4 in /home/codespace/anaconda3/lib/python3.9/site-packages (from mlflow-skinny==3.1.4->mlflow) (2.0.0)
Collecting databricks-sdk<1,>=0.20.0
  Downloading databricks_sdk-0.102.0-py3-none-any.whl (838 kB)
     |████████████████████████████████| 838 kB 85.1 MB/s eta 0:00:01
Collecting Mako
  Downloading mako-1.3.12-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 11.5 MB/s eta 0:00:01
Collecting typing-extensions<5,>=4.0.0
  Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 5.1 MB/s  eta 0:00:01
Requirement already satisfied: tomli in /home/codespace/anaconda3/lib/python3.9/site-packages (from alembic!=1.10.0,<2->mlflow) (1.2.2)
Collecting google-auth~=2.0
  Downloading google_auth-2.50.0-py3-none-any.whl (246 kB)
     |████████████████████████████████| 246 kB 68.2 MB/s eta 0:00:01
Collecting protobuf<7,>=3.12.0
  Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
     |████████████████████████████████| 323 kB 85.1 MB/s eta 0:00:01
Collecting requests<3,>=2.17.3
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 5.5 MB/s  eta 0:00:01
Requirement already satisfied: urllib3>=1.26.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from docker<8,>=4.0.0->mlflow) (1.26.9)
Collecting starlette<1.0.0,>=0.40.0
  Downloading starlette-0.49.3-py3-none-any.whl (74 kB)
     |████████████████████████████████| 74 kB 5.1 MB/s  eta 0:00:01
Collecting typing-inspection>=0.4.2
  Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Collecting annotated-doc>=0.0.2
  Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Requirement already satisfied: Jinja2>=2.10.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.11.3)
Requirement already satisfied: itsdangerous>=0.24 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.0.1)
Requirement already satisfied: Werkzeug>=0.15 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Flask<4->mlflow) (2.0.3)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 2.6 MB/s  eta 0:00:01
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (0.2.8)
Collecting cryptography>=38.0.3
  Downloading cryptography-48.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 42.8 MB/s eta 0:00:01
Collecting cffi>=2.0.0
  Downloading cffi-2.0.0-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216 kB)
     |████████████████████████████████| 216 kB 83.9 MB/s eta 0:00:01
Requirement already satisfied: pycparser in /home/codespace/anaconda3/lib/python3.9/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (2.21)
Collecting graphql-core<3.3,>=3.1
  Downloading graphql_core-3.2.8-py3-none-any.whl (207 kB)
     |████████████████████████████████| 207 kB 74.6 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from graphene<4->mlflow) (2.8.2)
Collecting graphql-relay<3.3,>=3.1
  Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Requirement already satisfied: zipp>=0.5 in /home/codespace/anaconda3/lib/python3.9/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.1.4->mlflow) (3.7.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/codespace/anaconda3/lib/python3.9/site-packages (from Jinja2>=2.10.1->Flask<4->mlflow) (2.0.1)

Requirement already satisfied: pyparsing>=2.2.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (3.0.4)
Requirement already satisfied: pillow>=6.2.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (9.0.1)
Requirement already satisfied: cycler>=0.10 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from matplotlib<4->mlflow) (1.3.2)
Collecting importlib_metadata!=4.7.0,<9,>=3.7.0
  Downloading importlib_metadata-8.7.1-py3-none-any.whl (27 kB)
Collecting zipp>=0.5
  Downloading zipp-3.23.1-py3-none-any.whl (10 kB)
Collecting opentelemetry-semantic-conventions==0.62b1
  Downloading opentelemetry_semantic_conventions-0.62b1-py3-none-any.whl (231 kB)
     |████████████████████████████████| 231 kB 84.7 MB/s eta 0:00:01
Requirement already satisfied: pytz>=2020.1 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pandas<3->mlflow) (2021.3)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/codespace/anaconda3/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.1.4->mlflow) (0.4.8)
Collecting pydantic-core==2.46.4
  Downloading pydantic_core-2.46.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 79.5 MB/s eta 0:00:01
Collecting annotated-types>=0.6.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: six>=1.5 in /home/codespace/anaconda3/lib/python3.9/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.1.4->mlflow) (2.0.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/codespace/anaconda3/lib/python3.9/site-packages (from scikit-learn<2->mlflow) (2.2.0)
Requirement already satisfied: joblib>=0.11 in /home/codespace/anaconda3/lib/python3.9/site-packages (from scikit-learn<2->mlflow) (1.1.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/codespace/anaconda3/lib/python3.9/site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (1.1.1)
Collecting anyio<5,>=3.6.2
  Downloading anyio-4.12.1-py3-none-any.whl (113 kB)
     |████████████████████████████████| 113 kB 86.3 MB/s eta 0:00:01
Collecting exceptiongroup>=1.0.2
  Downloading exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Collecting h11>=0.8
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: zipp, typing-extensions, importlib-metadata, exceptiongroup, cffi, typing-inspection, smmap, pydantic-core, opentelemetry-api, cryptography, anyio, annotated-types, starlette, requests, pydantic, protobuf, opentelemetry-semantic-conventions, h11, graphql-core, google-auth, gitdb, annotated-doc, uvicorn, sqlparse, opentelemetry-sdk, Mako, graphql-relay, gitpython, fastapi, databricks-sdk, cachetools, pyarrow, mlflow-skinny, gunicorn, graphene, docker, alembic, mlflow
  Attempting uninstall: zipp
    Found existing installation: zipp 3.7.0
    Uninstalling zipp-3.7.0:
      Successfully uninstalled zipp-3.7.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 4.1.1
    Uninstalling typing-extensions-4.1.1:
      Successfully uninstalled typing-extensions-4.1.1
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.11.3
    Uninstalling importlib-metadata-4.11.3:
      Successfully uninstalled importlib-metadata-4.11.3
  Attempting uninstall: cffi
    Found existing installation: cffi 1.15.0
    Uninstalling cffi-1.15.0:
      Successfully uninstalled cffi-1.15.0
  Attempting uninstall: cryptography
    Found existing installation: cryptography 3.4.8
    Uninstalling cryptography-3.4.8:
      Successfully uninstalled cryptography-3.4.8
  Attempting uninstall: anyio
    Found existing installation: anyio 3.5.0
    Uninstalling anyio-3.5.0:
      Successfully uninstalled anyio-3.5.0
  Attempting uninstall: requests
    Found existing installation: requests 2.27.1
    Uninstalling requests-2.27.1:
      Successfully uninstalled requests-2.27.1
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.1
    Uninstalling protobuf-3.19.1:
      Successfully uninstalled protobuf-3.19.1
  Attempting uninstall: google-auth
    Found existing installation: google-auth 1.33.0
    Uninstalling google-auth-1.33.0:
      Successfully uninstalled google-auth-1.33.0
  Attempting uninstall: cachetools
    Found existing installation: cachetools 4.2.2
    Uninstalling cachetools-4.2.2:
      Successfully uninstalled cachetools-4.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
anaconda-project 0.10.2 requires ruamel-yaml, which is not installed.
jupyter-server 1.13.5 requires anyio<4,>=3.1.0, but you have anyio 4.12.1 which is incompatible.
google-cloud-storage 1.31.0 requires google-auth<2.0dev,>=1.11.0, but you have google-auth 2.50.0 which is incompatible.
google-cloud-core 1.7.1 requires google-auth<2.0dev,>=1.24.0, but you have google-auth 2.50.0 which is incompatible.
google-api-core 1.25.1 requires google-auth<2.0dev,>=1.21.1, but you have google-auth 2.50.0 which is incompatible.
Successfully installed Mako-1.3.12 alembic-1.16.5 annotated-doc-0.0.4 annotated-types-0.7.0 anyio-4.12.1 cachetools-6.2.6 cffi-2.0.0 cryptography-48.0.0 databricks-sdk-0.102.0 docker-7.1.0 exceptiongroup-1.3.1 fastapi-0.128.8 gitdb-4.0.12 gitpython-3.1.50 google-auth-2.50.0 graphene-3.4.3 graphql-core-3.2.8 graphql-relay-3.2.0 gunicorn-23.0.0 h11-0.16.0 importlib-metadata-8.7.1 mlflow-3.1.4 mlflow-skinny-3.1.4 opentelemetry-api-1.41.1 opentelemetry-sdk-1.41.1 opentelemetry-semantic-conventions-0.62b1 protobuf-6.33.6 pyarrow-20.0.0 pydantic-2.13.4 pydantic-core-2.46.4 requests-2.32.5 smmap-5.0.3 sqlparse-0.5.5 starlette-0.49.3 typing-extensions-4.15.0 typing-inspection-0.4.2 uvicorn-0.39.0 zipp-3.23.1

In [5]:
import mlflow

In [6]:
mlflow.set_tracking_uri("sqlite:///mlflow.db")

In [7]:
mlflow.set_experiment("HousePricePrediction-01")

2026/05/22 07:40:02 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/05/22 07:40:02 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
INFO  [alembic.runtime.migration] Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
INFO  [alembic.runtime.migration] Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
INFO  [alembic.runtime.migration] Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
INFO  [alembic.runtime.migration] Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
INFO  [alembic.runtime.migration] Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
INFO  [alembic.runtime.migration] Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
INFO  [alembic.runtime.migration] Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
INFO  [alembic.runtime.migration] Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
INFO  [alembic.runtime.migration] Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
INFO  [alembic.runtime.migration] Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
INFO  [alembic.runtime.migration] Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
INFO  [alembic.runtime.migration] Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
INFO  [alembic.runtime.migration] Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
INFO  [alembic.runtime.migration] Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
INFO  [alembic.runtime.migration] Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
INFO  [alembic.runtime.migration] Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
INFO  [alembic.runtime.migration] Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
INFO  [alembic.runtime.migration] Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
INFO  [alembic.runtime.migration] Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments
INFO  [alembic.runtime.migration] Running upgrade 0584bdc529eb -> 400f98739977, add logged model tables
INFO  [alembic.runtime.migration] Running upgrade 400f98739977 -> 6953534de441, add step to inputs table
INFO  [alembic.runtime.migration] Running upgrade 6953534de441 -> bda7b8c39065, increase_model_version_tag_value_limit
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2026/05/22 07:40:03 INFO mlflow.tracking.fluent: Experiment with name 'HousePricePrediction-01' does not exist. Creating a new experiment.

<Experiment: artifact_location='/workspaces/mlops_sample/mlruns/1', creation_time=1779435603211, experiment_id='1', last_update_time=1779435603211, lifecycle_stage='active', name='HousePricePrediction-01', tags={}>

In [8]:
data = pd.read_csv('House Price Prediction Dataset.csv')

In [9]:
data.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64
dtypes: int64(7), object(3)
memory usage: 156.4+ KB

In [13]:
data['Location'].unique()

array(['Downtown', 'Suburban', 'Urban', 'Rural'], dtype=object)

In [14]:
data['Condition'].unique()

array(['Excellent', 'Good', 'Fair', 'Poor'], dtype=object)

In [15]:
data['Garage'].unique()

array(['No', 'Yes'], dtype=object)

In [17]:
final_df  = pd.get_dummies(data = data,drop_first=True, columns=['Location', 'Condition', 'Garage'], dtype='int')

In [18]:
final_df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price,Location_Rural,Location_Suburban,Location_Urban,Condition_Fair,Condition_Good,Condition_Poor,Garage_Yes
0,1,1360,5,4,3,1970,149919,0,0,0,0,0,0,0
1,2,4272,5,4,3,1958,424998,0,0,0,0,0,0,0
2,3,3592,2,2,3,1938,266746,0,0,0,0,1,0,0
3,4,966,4,2,2,1902,244020,0,1,0,1,0,0,1
4,5,4926,1,4,2,1975,636056,0,0,0,1,0,0,1

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, accuracy_score

In [30]:
features = final_df[final_df.columns.drop(['Id','Price', 'YearBuilt'])].values

In [31]:
target = final_df['Price'].values

In [34]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.20, random_state=42)

In [42]:
training_data_path = final_df.to_pickle('cleaned_training_data.pkl')

# Running Different Models

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors  import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

In [ ]:
##  Multiple Linear Regression

In [43]:
with mlflow.start_run():
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("trained_data_path", "/workspaces/mlops_sample/cleaned_training_data.pkl")
    linear_reg = LinearRegression()
    linear_reg.fit(X_train, y_train)
    y_prediction = linear_reg.predict(X_test)
    rmse = mean_squared_error(y_true=y_test, y_pred=y_prediction,squared=False)
    model_accuracy = accuracy_score(y_true=y_test, y_pred=y_prediction)
    mlflow.log_metric("rmse", rmse)
    mlflow.log_metric("accuracy_score", model_accuracy)

In [44]:
## Using other all algorithms

In [50]:
with mlflow.start_run(run_name="RandomForests-100-110estimators"):
    mlflow.set_tag("developer", "Praveen")
    mlflow.log_param("trained_data_path", "/workspaces/mlops_sample/cleaned_training_data.pkl")
    for i in range(100,111):
        rf = RandomForestRegressor(n_estimators=i)
        rf_model = rf.fit(X_train, y_train)
        y_prediction = rf_model.predict(X_test)
        rmse = mean_squared_error(y_true=y_test, y_pred=y_prediction,squared=False)
        mlflow.sklearn.log_model(sk_model = rf_model)
        mlflow.log_metric("rmse", rmse)
        mlflow.log_metric("n_estimators", i)

2026/05/22 10:19:23 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpnvz0bx57/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:26 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp6_pjbm8p/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:28 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp36mrcjq5/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:31 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp17z6ip9q/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:33 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpsalvhg7j/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:36 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpicq3vpn0/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:39 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpz_n27tfv/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:42 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp12_c5yz8/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:44 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpkjrbp8w6/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:47 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpcbb3lak7/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/05/22 10:19:50 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpx8l70hp9/model/model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.0.2', 'cloudpickle==2.0.0']. Set logging level to DEBUG to see the full traceback.
2026/05/22 10:19:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [52]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-2.1.4-py3-none-manylinux_2_28_x86_64.whl (223.6 MB)
     |████████████████████████████████| 223.6 MB 2.2 kB/s  eta 0:00:011   |██████▊                         | 46.8 MB 12.4 MB/s eta 0:00:15     |█████████████▏                  | 92.0 MB 108.8 MB/s eta 0:00:02     |████████████████████            | 139.3 MB 108.8 MB/s eta 0:00:016.4 MB/s eta 0:00:01     |██████████████████████████████▏ | 210.6 MB 86.4 MB/s eta 0:00:01
Collecting nvidia-nccl-cu12
  Downloading nvidia_nccl_cu12-2.30.4-py3-none-manylinux_2_18_x86_64.whl (300.2 MB)
     |████████████████████████████████| 300.2 MB 20 kB/s s eta 0:00:012     |█████████████████████▏          | 198.8 MB 80.4 MB/s eta 0:00:02     |█████████████████████▌          | 201.5 MB 80.4 MB/s eta 0:00:02     |██████████████████████▋         | 212.2 MB 80.4 MB/s eta 0:00:024.7 MB/s eta 0:00:01ta 0:00:01     |██████████████████████████████▌ | 286.6 MB 94.7 MB/s eta 0:00:01��███████████▎| 293.0 MB 94.7 MB/s eta 0:00:01
Requirement already satisfied: scipy in /home/codespace/anaconda3/lib/python3.9/site-packages (from xgboost) (1.7.3)
Requirement already satisfied: numpy in /home/codespace/anaconda3/lib/python3.9/site-packages (from xgboost) (1.21.5)
Installing collected packages: nvidia-nccl-cu12, xgboost
Successfully installed nvidia-nccl-cu12-2.30.4 xgboost-2.1.4

In [53]:
import xgboost as xgb

In [55]:
from xgboost import XGBRegressor

In [56]:
mlflow.xgboost.autolog()

In [59]:
model = xgb.XGBRegressor(
    n_estimators=100, 
    learning_rate=0.1, 
    max_depth=5, 
    objective='reg:squarederror'
)

with mlflow.start_run():
    model.fit(X_train, y_train, verbose=False)
    pred  = model.predict(X_test)
    rmse = mean_squared_error(y_true=y_test, y_pred=pred,squared=False)
    mlflow.log_metric("rmse", rmse)

2026/05/22 10:56:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/22 10:56:21 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/codespace/anaconda3/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [10:56:21] WARNING: /workspace/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats."
2026/05/22 10:56:26 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp0r_lekol/model, flavor: xgboost). Fall back to return ['xgboost==2.1.4']. Set logging level to DEBUG to see the full traceback.

In [60]:
model = xgb.XGBRegressor(
    n_estimators=100, 
    learning_rate=0.1, 
    max_depth=5)

model.fit(X_train, y_train, verbose=False)
pred  = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_true=y_test, y_pred=pred))
print(rmse)

2026/05/22 11:08:14 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '65bcc53adfce466ab66b0a14ebb67f2c', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current xgboost workflow
2026/05/22 11:08:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/22 11:08:14 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/codespace/anaconda3/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [11:08:14] WARNING: /workspace/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats."
2026/05/22 11:08:16 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp7duf_x4f/model, flavor: xgboost). Fall back to return ['xgboost==2.1.4']. Set logging level to DEBUG to see the full traceback.

298052.78295970766